version: 2.1

aliases:
  - &defaults
    docker:
      - image: cimg/node:15.10.0

  - &cache_key_node_modules
    key: v1-node_modules-{{ checksum "yarn.lock" }}

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Linter
          command: yarn run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: yarn run test
  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Unit tests with coverage report
          command: yarn run coverage
  publish_coverage:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Upload coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
workflows:
  workflow:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - coverage:
          requires:
            - dependencies
      - publish_coverage:
          requires:
            - coverage
